export const countries = {
  USA: "United States",
  CAN: "Canada",
  MEX: "Mexico",
  BRA: "Brazil",
  ARG: "Argentina",
  DEU: "Germany",
  FRA: "France",
  ESP: "Spain",
  ITA: "Italy",
  IND: "India",
  CHN: "China",
  JPN: "Japan",
  AUS: "Australia",
  ZAF: "South Africa",
  RUS: "Russia",
  GBR: "United Kingdom",
  KOR: "South Korea",
  NLD: "Netherlands",
  SWE: "Sweden",
  CHE: "Switzerland",
  NOR: "Norway",
  DNK: "Denmark",
  FIN: "Finland",
  AUT: "Austria",
  BEL: "Belgium",
  CZE: "Czech Republic",
  POL: "Poland",
  PRT: "Portugal",
  TUR: "Turkey",
  GRC: "Greece",
  HUN: "Hungary",
  ROU: "Romania",
};
